id: 9837d57d560b4208ac89fc297ea5e280
initial_creation_type: ebook
created_at: 8/09/2021
last_modified_at: 25/11/2021
source_metadata:
  title: སྙན་ངག་གི་ཚིག་རྒྱན་རབ་གསལ་སྣང་བ་བཞུགས།
  subtitle: སྙན་ངག་གི་ཚིག་རྒྱན་རབ་གསལ་སྣང་བ་བཞུགས།
  authors:
  - སྙན་ངག་གི་ཚིག་རྒྱན་རབ་གསལ་སྣང་བ་བཞུགས།
  collection: Pema Gyurme Gyatso
  publisher: Mindroling Publication
  id: MIN-PG04
  cover: tmp0nvzgipr.jpg
  credit: tmp4h8c73yc.jpg
